### ISSUE TITLE
Posts on the "Start." page always preflix url with localhost instead of the bound address

### ISSUE THREAD

**Issue by sn0ot** [colorchestra/smol#17]
# Setup

- Hugo running on Raspberry Pi 3 (Arch Linux Arm)
  - deploy server with `hugo server -D --bind=192.168.10.10`
  - in config.toml `baseURL = "http://192.168.10.10/"`
- View webpage from other machine on the network
  - `http://192.168.10.10:1313` takes me to the website hosted on the RPi3. I can navigate most links. 
    - For example when navigating to a post from the "post header", url is `http://192.168.10.10:1313/posts/first_post/`
    - When navigating to the same post from the "Start. Header", url is `localhost:1313/posts/first_post/`

Same issue to any link that displays the "title"

**Comment by colorchestra** [comment]
Hey @sn0ot, have you set the `BaseUrl` setting in your `config.toml`? The content of that variable is what the created links are based on.

**Comment by sn0ot** [comment]
Hiya @colorchestra, 
Yup I set my base url. As mentioned in the original post I tried `baseURL = "http://192.168.10.10/"` but I also tried different capitalization as you mentioned, like so `BaseUrl = "http://192.168.10.10/"` 

Not sure the variables are case sensitive but I tried anyway, unfortunately I know nothing about web design or hugo outside of the `config.toml`. 

How can I help debug this? Does hugo provide a log when building a site?

**Comment by colorchestra** [comment]
Well, "As mentioned in the original post" - I can see that you only edited that in after my last reply ;)

The problem is likely this: https://discourse.gohugo.io/t/localhost-links-being-generated/1059/2
Hugo ignores the settings in the config.toml when run as `hugo server`. If I add `--baseUrl=192.168.x.x`, it works for me.

**Comment by sn0ot** [comment]
Passing the `--baseUrl` parameter to `hugo sever` did the trick! Thank you very much!


Not sure of our miscommunication. My initial post was edited to include and clarify 
> Same issue to any link that displays the "title"

I was not trying to be rude in pointing you to original post. I figured I did a poor job explaining my issue and didn't get the point across clearly as I'm a new hugo user.

**Comment by colorchestra** [comment]
Hey @sn0ot, sorry for my snarky reply. I now understand what you meant, thanks for clarifying! I hope you have a good experience in you further journey to discover Hugo.

**Comment by sn0ot** [comment]
Thank you friend :)
