### ISSUE TITLE
Improve dark mode colors

### ISSUE THREAD

**Issue by colorchestra** [colorchestra/smol#18]
The colors in the dark theme were taken directly from the source theme and aren't that great. I could imagine changing them to #FFFFFF on #000000 or something, with the links still in blue if that's not too hard to read

**Comment by seshaljain** [comment]
Would it make sense to use CSS variables here? It will allow for easier theme customization as well.

**Comment by sumnerevans** [comment]
Feel free to steal the dark mode colors from my website: https://sumnerevans.com.

The background is `#282828` and the foreground is `#dadada` which I think is easier on the eyes than pure black and white.

**Comment by colorchestra** [comment]
Hey all, thanks for your input! I've finally updated the theme with some nicer dark mode colors. They are set via CSS variables which are indeed a bit nicer to work with. I'm not fully sure how much I like the visited links being bright red, but I guess I'll have to sit with it for a bit and see if it grows on me.
