### ISSUE TITLE
Upstream feature ideas from my fork?

### ISSUE THREAD

**Issue by sumnerevans** [colorchestra/smol#20]
Thank you for this great theme! I've made a few modifications to it for my own website (https://sumnerevans.com), and I'd like to know whether you are interested in any of these changes being upstreamed.

Some of the features require JavaScript, which I know is an anti-goal of this theme, so if you do not want me to try and upstream those features, that is fine (I'll continue to maintain them on my fork). However, as I upstream the changes I will make sure that no JavaScript is included by default (users will have to explicitly enable features which require JavaScript).

Other features may be too divergent from the intent of this theme, so I understand if you do not want me to try and upstream them.

Here are a list of the modifications that I have made on my site that could be of interest:

* Dark/light mode switch functionality (see the footer of my website, requires JavaScript but falls back to CSS media queries)
* Isso comments integration (requires JavaScript)
* Full-text search (via [lunr](https://lunrjs.com/), requires JavaScript)
* Convert the CSS to SCSS
* Styles for [reStructuredText admonitions](https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions). There are a few admonition examples in this post: https://sumnerevans.com/posts/school/2021-hspc/ (I am using FontAwesome, but that can be an optional dependency)
* Opengraph metadata
* Summary image
* MathJax support
* Updated header with profile picture
* Options to change the delimiter between items in the nav menus
* Options to change the datetime format on posts
* Option to include category for posts
* Option to add word count for posts
* Option to add reading time for posts
* Use commas to separate tags

Please let me know if any of these are worth upstreaming and I can work on creating separate issues and/or PRs for them.

**Comment by colorchestra** [comment]
Hi @sumnerevans,

sorry for taking so long to get back! Your site looks great. In my opinion, your fork of smol is worth getting released as a theme on its own :)
As you have said yourself, some of your improvements don't really fit the idea I was going for with this theme. However, I'd happily upstream the following:

- Opengraph metadata
- Updated header with profile picture
- Options to change the delimiter between items in the nav menus
- Options to change the datetime format on posts
- Option to add word count for posts
- Option to add reading time for posts
- Use commas to separate tags

If you get around to it, I'd love to have these features.

Thank you!
