### ISSUE TITLE
Is this theme abondoned?

### ISSUE THREAD

**Issue by handmeatowel** [colorchestra/smol#28]
Is this theme abondoned? If so, are there any forks?

**Comment by colorchestra** [comment]
Hello @handmeatowel ,

the theme is not abandoned, although I admittedly I don't check in here very often. As far as I'm aware though, it still works well. There are many forks here on Github, but I haven't checked them so there isn't one I can recommend in particular. [This fork](https://github.com/sumnerevans/smol) is very cool but is now quite different from the original vision I had for it.
