### ISSUE TITLE
how to use dark mode?

### ISSUE THREAD

**Issue by kevung** [colorchestra/smol#29]
Hello, 
thank you very much for the smol theme.
How do you use this theme in dark mode? (this is not written in the documentation).
Thank you.

**Comment by colorchestra** [comment]
Hey @kevung,

dark mode is based on your operating system's setting. If your OS is set to dark mode, the theme will do the same. It works using the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) setting.
